services:
  jenkins:
    image: jenkins/jenkins:2.442-jdk17
    env_file:
      - ".env"
    ports:
      - "${JENKINS_PORT}:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/local/bin/docker-compose:/usr/bin/docker-compose"

volumes:
  jenkins_home:
