version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    env_file:
      - ".env"
    ports:
      - "${JENKINS_PORT}:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"

volumes:
  jenkins_home:
